Prepare for plugin dynamic
ant-druha/intellij-powershell pull request #129
Opened 2023-09-04 08:00 UTC by VladRassokhin

2023-09-04 21:17 UTC, ForNeVeR requested changes

2023-09-04 21:17 UTC, ForNeVeR commented on build.gradle.kts
> +    autoReloadPlugins.set(true)
If I understand correctly, currently this doesn't work on Linux and macOS, right? So, let's maybe make this conditional on the current OS, or disable it until #121 is resolved? What do you think?

2023-09-04 21:17 UTC, ForNeVeR commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/ide/EditorEventManager.kt
> +      return editor.getUserData(EDITOR_EVENT_MANAGER_KEY)
Hey, will this work correctly if the plugin is unloaded? Is there some special treatment in the platform for the user data keys introduced by the plugins?

2023-09-04 21:17 UTC, ForNeVeR commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/languagehost/EditorServicesLanguageHostStarter.kt
> +    return sessionCount.getAndIncrement()
Ha, a good catch! 👍

2023-09-05 07:52 UTC, VladRassokhin commented on build.gradle.kts
> +    autoReloadPlugins.set(true)
I've tested on macOS, as I've no other OS. :)
While the plugin is marked as `requires-restart=true`, those options would be no-op, AFAIU.

2023-09-05 07:53 UTC, VladRassokhin commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/languagehost/EditorServicesLanguageHostStarter.kt
> +    return sessionCount.getAndIncrement()
I've just grepped for 'volatile' ;)

2023-09-05 09:08 UTC, VladRassokhin commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/ide/EditorEventManager.kt
> +      return editor.getUserData(EDITOR_EVENT_MANAGER_KEY)
No idea :)
But if we remove user data in `dispose`, it should be safe.

2023-09-05 09:38 UTC, ForNeVeR commented on build.gradle.kts
> +    autoReloadPlugins.set(true)
Ok then, I'll check.

2023-09-05 09:39 UTC, ForNeVeR commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/ide/EditorEventManager.kt
> +      return editor.getUserData(EDITOR_EVENT_MANAGER_KEY)
Ok, I'll take another look at the related code.

2023-09-06 22:15 UTC, ForNeVeR approved these changes
Thanks!

2023-09-06 22:15 UTC, merged