Fix deprecated API usages
ant-druha/intellij-powershell pull request #141
Opened 2023-09-20 14:53 UTC by VladRassokhin

I've run `./gradle runPluginVerifier` and it shows zero deprecated usages agains IC-232.9921.47 :)

2023-09-20 20:42 UTC, ForNeVeR requested changes

2023-09-20 20:42 UTC, ForNeVeR commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/LSPInitMain.kt
> +            .also { endpoint -> Disposer.register(lspInitMain, endpoint) }
This is not required and is even harmful: it will effectively steal the `LanguageServerEndpoint` from its previous disposable parent (the `PluginProjectDisposableRoot`).

2023-09-20 20:42 UTC, ForNeVeR commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/languagehost/LanguageServerEndpoint.kt
>      addShutdownHook()
Let's drop this hook while we are at it.

2023-09-20 20:46 UTC, ForNeVeR approved these changes
Thanks!

2023-09-20 20:52 UTC, merged

2023-09-21 08:18 UTC, VladRassokhin commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/LSPInitMain.kt
> +            .also { endpoint -> Disposer.register(lspInitMain, endpoint) }
Wow, I though it's possible to have several disposable parents.

2023-09-21 09:42 UTC, ForNeVeR commented on src/main/kotlin/com/intellij/plugin/powershell/lang/lsp/LSPInitMain.kt
> +            .also { endpoint -> Disposer.register(lspInitMain, endpoint) }
Nope, it is not possible (check the docs on `Disposer::register`: it is supposed to "override" the parent object, even though in practice it's almost always a mistake).